@extends('admin.layout')
@section('title', 'Admin - Asked Question')

@section('content')
    <div class="as-w-100">
        <!-- Header -->
        <div class="header">
            <div class="header-left">
                <button class="sidebar-toggle as-app-cursor as-flex as-align-center" id="sidebarToggle" style="display: inline-flex">
                    <i style="font-size: 24px" class="fas fa-bars"></i>
                </button>
                <h2>Asked Question</h2>
            </div>
            <div class="user-info">
                <div class="user-avatar">AD</div>
                <div>
                    <div style="font-weight: 600;">{{ $admin[0]->admin_username }}</div>
                    <div style="font-size: 12px; color: var(--gray);">{{ $admin[0]->admin_role }}</div>
                </div>
            </div>
        </div>

        <!-- Stats Cards -->
        <div class="stats-container">
            <div class="stat-card">
                <div class="stat-icon primary">
                    <i class="fas fa-question-circle"></i>
                </div>
                <div class="stat-info">
                    <h3 id="total-question">....</h3>
                    <p>Total Questions</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon success">
                    <i class="fas fa-check-circle"></i>
                </div>
                <div class="stat-info">
                    <h3 id="total-answered">....</h3>
                    <p>Answered</p>
                </div>
            </div>
            <div class="stat-card">
                <div class="stat-icon warning">
                    <i class="fas fa-clock"></i>
                </div>
                <div class="stat-info">
                    <h3 id="total-pending">....</h3>
                    <p>Pending</p>
                </div>
            </div>
        </div>
        
        <!-- Questions Table -->
        <div class="content-section">
            <div class="section-header">
                <h3>Recent Questions</h3>
            </div>
            
            <div class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Course</th>
                            <th>Topic</th>
                            <th>Student</th>
                            <th>Question</th>
                            <th>Answer</th>
                            
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="question-answer-div">
                        
                    </tbody>
                </table>
            </div>
            
            <div class="pagination">
                <div class="pagination-info" id="paginationInfo">
                    Showing 0 to 0 of 0 entries
                </div>
                <div class="pagination-controls" id="paginationControls">
                    <!-- Pagination buttons will be generated by JavaScript -->
                </div>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    <script>
        getAskedQuenstion();

        // Pagination variables
        var qaData = [];
        let currentPage = 1;
        const itemsPerPage = 10;
        let filteredData = [];

        function getAskedQuenstion() {
            let questionAnswerDiv = document.getElementById('question-answer-div');
            questionAnswerDiv.innerHTML = `
                    <tr>
                        <td colspan="100%" style="text-align:center; padding:10px;">
                            <i style="font-size:25px;" class="fa-solid fa-spinner fa-spin"></i>
                        </td>
                    </tr>
                `;

            axios.get('/admin/get-asked-question')
                .then(response => {
                    questionAnswerDiv.innerHTML = '';

                    if (response.data.length === 0) {
                        questionAnswerDiv.innerHTML = `
                            <tr>
                                <td colspan="100%" style="text-align:center; padding:10px;">
                                    No question found.
                                </td>
                            </tr>`;
                        return;
                    }

                    qaData = response.data.asked_questions;
                    document.getElementById('total-question').innerText = response.data.total_question;
                    document.getElementById('total-answered').innerText = response.data.total_answered;
                    document.getElementById('total-pending').innerText = response.data.total_pending;
                    filteredData = [...qaData];
                    initializePagination();
                        
                })
        }

        // Function to render the table with current page data
        function renderTable(filterValue = null) {
            // Calculate start and end indices for current page
            const startIndex   = (currentPage - 1) * itemsPerPage;
            const endIndex     = Math.min(startIndex + itemsPerPage, filteredData.length);
            const currentItems = filteredData.slice(startIndex, endIndex);
            
            // Clear the table body
            const tableBody = document.getElementById('question-answer-div');
            tableBody.innerHTML = '';
            
            // Populate the table with current page data
            currentItems.forEach(item => {
                const row = document.createElement('tr');
                // Add your row content here based on your data structure
                row.innerHTML = `
                    <tr>
                        <td>
                            <span class="course-badge as-check-language" id="coursename${item.id}">${item.course_name}</span>
                        </td>
                        <td class="as-check-language">${item.topic_name}</td>
                        <td class="as-check-language" style="white-space: nowrap;">${item.student_name != null ? item.student_name : 'Anonymous'}</td>
                        <td class="as-check-language" class="question-preview">${item.question}</td>
                        <td class="as-check-language">${item.answer}</td>
                        
                        <td><span class="status-badge ${item.answer == '' ? 'pending' : 'answered'}">${item.answer == '' ? 'Pending' : 'Answered'}</span></td>
                        <td>
                            <div class="action-buttons">
                                <button class="action-btn as-app-cursor edit" title="Edit" onclick="showModal('add-reply${item.id}')">
                                    <i class="fas fa-edit"></i>
                                </button>
                                <button class="action-btn as-app-cursor view" title="View" onclick="deleteQuestion(${item.id})">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </div>
                        </td>
                    </tr>

                    <div class="as-modal" id="add-reply${item.id}" style="display: none">
                        <div class="info-section as-bg-white as-shadow-lw as-p-20px as-w-50 md:as-w-90 as-mt-10px as-brr-5px">

                            <div class="as-modal-child">
                                <div class="as-mt-10px">
                                    <div class="as-mb-5px"><b>Reply</b></div>
                                    <input type="text" id="reply${item.id}" class="as-input" placeholder="Enter Question Reply">
                                </div>
                            </div>
                            <div class="as-mt-10px as-text-right">
                                <button class="as-btn as-app-cursor as-bg-cancel" onclick="hideModal('add-reply${item.id}')">Cancel</button>
                                <button class="as-btn as-app-cursor" onclick="addReply(${item.id})">Add</button>
                            </div>
                        </div>
                    </div>
                `;
                tableBody.appendChild(row);
            });
            
            
            // Update pagination info
            const paginationInfo = document.getElementById('paginationInfo');
            const start = filteredData.length > 0 ? startIndex + 1 : 0;
            const end = endIndex;
            paginationInfo.textContent = `Showing ${start} to ${end} of ${filteredData.length} entries`;
        }

        // Function to setup pagination controls
        function setupPagination() {
            const paginationControls = document.getElementById('paginationControls');

            // Clear existing pagination controls
            paginationControls.innerHTML = '';

            const totalPages = Math.ceil(filteredData.length / itemsPerPage);

            // Previous button
            const prevButton = document.createElement('button');
            prevButton.innerHTML = '<i class="fas fa-chevron-left"></i>';
            prevButton.disabled = currentPage === 1;
            prevButton.addEventListener('click', () => {
                if (currentPage > 1) {
                    currentPage--;
                    renderTable();
                    setupPagination();
                }
            });
            paginationControls.appendChild(prevButton);

            // Page buttons
            const maxVisiblePages = 5;
            let startPage = Math.max(1, currentPage - Math.floor(maxVisiblePages / 2));
            let endPage = Math.min(totalPages, startPage + maxVisiblePages - 1);

            // Adjust start page if we're near the end
            if (endPage - startPage + 1 < maxVisiblePages) {
                startPage = Math.max(1, endPage - maxVisiblePages + 1);
            }

            // First page button if needed
            if (startPage > 1) {
                const firstPageButton = document.createElement('button');
                firstPageButton.textContent = '1';
                firstPageButton.addEventListener('click', () => {
                    currentPage = 1;
                    renderTable();
                    setupPagination();
                });
                paginationControls.appendChild(firstPageButton);

                // Ellipsis if needed
                if (startPage > 2) {
                    const ellipsis = document.createElement('button');
                    ellipsis.textContent = '...';
                    ellipsis.disabled = true;
                    paginationControls.appendChild(ellipsis);
                }
            }

            // Page number buttons
            for (let i = startPage; i <= endPage; i++) {
                const pageButton = document.createElement('button');
                pageButton.textContent = i;
                if (i === currentPage) {
                    pageButton.classList.add('active');
                }
                pageButton.addEventListener('click', () => {
                    currentPage = i;
                    renderTable();
                    setupPagination();
                });
                paginationControls.appendChild(pageButton);
            }

            // Last page button if needed
            if (endPage < totalPages) {
                // Ellipsis if needed
                if (endPage < totalPages - 1) {
                    const ellipsis = document.createElement('button');
                    ellipsis.textContent = '...';
                    ellipsis.disabled = true;
                    paginationControls.appendChild(ellipsis);
                }

                const lastPageButton = document.createElement('button');
                lastPageButton.textContent = totalPages;
                lastPageButton.addEventListener('click', () => {
                    currentPage = totalPages;
                    renderTable();
                    setupPagination();
                });
                paginationControls.appendChild(lastPageButton);
            }

            // Next button
            const nextButton = document.createElement('button');
            nextButton.innerHTML = '<i class="fas fa-chevron-right"></i>';
            nextButton.disabled = currentPage === totalPages;
            nextButton.addEventListener('click', () => {
                if (currentPage < totalPages) {
                    currentPage++;
                    renderTable();
                    setupPagination();
                }
            });
            paginationControls.appendChild(nextButton);
        }

        // Function to reset pagination (call this when filters change)
        function resetPagination() {
            currentPage = 1;
            renderTable();
            setupPagination();
        }

        // Function to update data and refresh pagination
        function updateData(newData) {
            filteredData = [...newData];
            resetPagination();
        }

        function initializePagination(filterValue = null) {
            renderTable(filterValue);
            setupPagination();
        }

        // Initialize pagination on page load
        document.addEventListener('DOMContentLoaded', function() {
            getAskedQuenstion();
        });

        function addReply(questionId) {
            let reply = document.getElementById('reply' + questionId).value;
            if (reply === '') {
                alert('Please enter reply');
                return;
            }

            axios.post('/admin/asked-question/reply', {
                question_id: questionId,
                reply: reply
            }).then(res => {
                if (res.data.status === 'success') {
                    alert('Reply added successfully');
                    hideModal('add-reply' + questionId);
                    getAskedQuenstion();
                } else {
                    alert('Something went wrong. Please try again.');
                }
            })
        }

        function deleteQuestion(questionId) {
            if (confirm('Do you want to delete the question?')) {
                axios.post('/admin/asked-question/delete', {
                    question_id: questionId
                }).then(res => {
                    if (res.data.status === 'success') {
                        alert('Question deleted successfully');
                        getAskedQuenstion();
                    } else {
                        alert('Something went wrong. Please try again.');
                    }
                })
            }
        }
    </script>
@endsection